#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32

def callback_down(data):
    rospy.loginfo("We got " + str(data.data) + " key down")

def callback_up(data):
    rospy.loginfo("We got " + str(data.data) + " key up")

sub_down = rospy.Subscriber("keydown_pub", Int32, callback_down)
sub_up = rospy.Subscriber("keyup_pub", Int32, callback_up)

rospy.init_node("keyboard_subscriber")
rospy.spin()